export const LogoSvg = require('./logo.svg')
export const icInitialLetterLogo = require('./ic_initialLogo.svg')
export const icClosedEyes = require('./ic_eyesClosed.svg')
export const icOpenedEyes = require('./ic_eyesOpened.svg')
export const icEllipsis = require('./ic_ellipsis.svg')
